trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- script: |
    dotnet restore HelloFunction/HelloFunction.csproj
    dotnet build HelloFunction/HelloFunction.csproj --configuration $(buildConfiguration)
  displayName: 'Build Azure Function'

- script: |
    dotnet test
  displayName: 'Run Tests'
